In [8]:
#Задача №1
n = int(input('Введите число:'))
l = [1, 2, 3, 4, 5, 11, 53, 66]
def func1(l, n):
    temp = list()
    for i in l:
        if i % n == 0:
            temp.append(i)
    return temp
print('Выходной список:', func1(l, n))

Введите число:11
Выходной список: [11, 66]

In [24]:
#Задача №2
l1 = list(range(1,11))
print(l1)
def func2(l1):
    ll1 = list()
    for i in range(len(l1)):
        if (i + 1) %5 == 0:
            ll1.append(l1[i] * 2)
        elif (i + 1) %3 == 0:
            continue  
        elif (i + 1) % 5 != 0 or (i + 1) % 3 != 0:
            ll1.append(l1[i])
    return ll1
print('Итог:', func2(l1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Итог: [1, 2, 4, 10, 7, 8, 20]

In [9]:
#Задача №3
z = int(input('Введите число:'))
l2 = [1, 2, 455, 6, 6, 1, 6]
def func3(l2, z):
    return l2.count(z)
print('Кол-во повторений:', func3(l2, z))

Введите число:1
Кол-во повторений: 2

In [10]:
#Задача №4
x = list(range(1, 13))
print('Старт:', x)
def func4(x):
    i = 0
    while (i + 2) <= len(x):
        x[i], x[i + 2] = x[i + 2], x[i]
        i += 3
    return x
print('Вывод:', func4(x))

Старт: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Вывод: [3, 2, 1, 6, 5, 4, 9, 8, 7, 12, 11, 10]

In [11]:
#Задача №5
s1 = [11, 2, 3, 47, 55, 77]
s2 = [55, 76, 1, -67, 99, 22]
def func5(s1, s2):
    s3 = list()
    i = 0
    while i < len(s1 + s2)/2:
        s3.append(s1[i] - s2[i])
        i += 1
    return s3
print('Выходные данные:', func5(s1, s2))

Выходные данные: [-44, -74, 2, 114, -44, 55]

In [12]:
#Задача №6
L = [1, 2, 5, 6, 4, 3, 3, 5, 4, 5, 7]
def func6(L):
    ss = list()
    works = list()
    for i in L:
        if i in works:
            continue
        ss.append(L.count(i))
        works.append(i)
    return ss
print('Вывод:', func6(L))

Вывод: [1, 1, 3, 1, 2, 2, 1]

In [13]:
#Задача №7
LL = [-10, 16, 13, 3, 0, -16, 1, -6, 0, 4, 0]
def func7(LL):
    new_L = list()
    for i in LL:
        if i > 0:
            new_L.append(i)
    new_L.sort()
    return new_L
print('Вывод:', func7(LL))

Вывод: [1, 3, 4, 13, 16]

In [14]:
#Задача №8
N = int(input('Введите число:'))
Q = list(range(0, N - 3))
print('Исходный список:', Q)
def func8(N, Q):
    temp1 = list()
    for i in range(0, N):
        if i not in Q:
            temp1.append(i)
    return temp1
print('Результат:', func8(N, Q))

Введите число:15
Исходный список: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
Результат: [12, 13, 14]

In [15]:
#Из папки на github с текущим заданием загрузить файл data_1.csv
import numpy as np
import pandas as pd
import matplotlib

data=pd.read_csv("https://raw.githubusercontent.com/junaart/ForStudents/master/Big_Data/Seminar_4/data_1.csv")
display(data)

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
0,Алистратов А.А.,27.10.1975,м,08.09.1997,4000,женат,1.0
1,Анохин Н.И.,11.12.1948,м,23.05.1986,5000,разведен,1.0
2,Антонова И.П.,04.12.1951,ж,09.05.1988,4300,замужем,1.0
3,Артемова Г.А.,06.08.1979,ж,05.09.1997,4500,незамужем,NaN
4,Афоничева Л.К.,09.01.1952,ж,05.10.1985,4900,замужем,1.0
...,...,...,...,...,...,...,...
95,Шафеева Н.К.,29.07.1939,ж,09.12.1985,4500,замужем,1.0
96,Шиманюк Н.И.,06.11.1979,м,23.11.1998,4000,холост,NaN
97,Элиава Т.М.,19.05.1981,м,10.09.1997,3700,холост,NaN
98,Якимова Н.М.,16.05.1973,ж,07.09.1999,3000,замужем,2.0
99,Яфарова Т.Н.,04.09.1945,ж,21.03.1986,4000,замужем,2.0

In [16]:
#Cформировать два отдельных DataFrame из мужчин и женщин. Для женщин рассчитать и добавить в соответствующий DataFrame
#столбец возраста. Для мужчин рассчитать и добавить в соответствующий DataFrame столбец стажа.
women_frame = pd.DataFrame(columns = data.columns)
women_frame = data[data['Пол'] == 'ж'].copy()
display(women_frame)
men_frame = pd.DataFrame(columns = data.columns)
men_frame = data[data['Пол'] == 'м'].copy()
display(men_frame)

for label in women_frame.index:
    women_frame.loc[label,'Возраст'] = 2021 - int(women_frame.loc[label,'Дата рождения'][6:10])
display(women_frame)

for label in men_frame.index:
    men_frame.loc[label,'Стаж'] = 2021 - int(men_frame.loc[label,'Дата рождения'][6:10])
display(men_frame)

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
2,Антонова И.П.,04.12.1951,ж,09.05.1988,4300,замужем,1.0
3,Артемова Г.А.,06.08.1979,ж,05.09.1997,4500,незамужем,NaN
4,Афоничева Л.К.,09.01.1952,ж,05.10.1985,4900,замужем,1.0
5,Афоничева Л.В.,08.06.1978,ж,22.09.1998,3000,замужем,NaN
7,Бегунова С.А.,20.05.1973,ж,11.09.1997,4400,замужем,1.0
9,Бизюкова Г.П.,01.05.1957,ж,09.06.1985,4000,замужем,1.0
11,Быкова И.А.,12.01.1958,ж,25.07.1994,5600,замужем,2.0
12,Вантеева Л.В.,12.01.1958,ж,25.07.1994,4500,замужем,2.0
14,Васильева Е.Г.,09.01.1952,ж,05.10.1985,4900,замужем,1.0
15,Вуколова О.В.,14.02.1963,ж,01.11.1990,3500,замужем,2.0
16,Гаранина Г.П.,05.06.1965,ж,12.06.1985,3500,замужем,1.0
17,Гордеева Н.А.,16.11.1953,ж,05.03.1985,4100,замужем,NaN
19,Грачева О.Е.,13.05.1967,ж,14.09.2000,4500,замужем,NaN
21,Гусева И.А.,06.06.1956,ж,09.12.1987,4900,разведена,1.0
22,Дзебоева Н.А.,20.08.1954,ж,09.12.1985,4600,замужем,2.0
23,Дмитриева З.Е.,22.09.1980,ж,09.05.1998,4700,незамужем,NaN
24,Дробикова С.А.,11.07.1961,ж,21.03.1986,5600,замужем,1.0
26,Ермолаева Е.И.,01.05.1967,ж,23.05.1986,4300,незамужем,NaN
28,Зайцева Т.Н.,22.09.1980,ж,09.05.1998,3800,незамужем,NaN
29,Захарова В.В.,24.06.1964,ж,15.09.1995,4300,замужем,2.0
30,Истратова Е.Н.,25.03.1964,ж,05.03.1985,3000,замужем,2.0
32,Ковалева М.Г.,20.08.1959,ж,05.10.1995,4500,замужем,1.0
33,Колганова В.В.,07.08.1951,ж,04.08.1980,4450,замужем,1.0
35,Конюхова Л.Н.,17.01.1951,ж,06.09.1985,3000,разведена,1.0
36,Корчагина О.С.,05.05.1967,ж,04.05.1984,4400,замужем,1.0
37,Курдина С.Х.,16.11.1953,ж,05.03.1985,4100,замужем,NaN
38,Лазькова Л.В.,06.11.1978,ж,20.12.1992,4700,незамужем,NaN
39,Ларшина Н.П.,06.12.1978,ж,08.08.1997,4000,незамужем,1.0
40,Леонова Е.И.,13.07.1947,ж,09.12.1990,3000,замужем,3.0
49,Михайлова Т.В.,06.02.1954,ж,23.05.1995,3000,замужем,3.0
50,Моисеева В.Б.,07.08.1962,ж,04.09.1980,4450,замужем,2.0
52,Муравьева В.С.,03.10.1955,ж,04.08.1980,3000,незамужем,NaN
53,Нарольская Т.С.,14.05.1962,ж,04.05.1994,4000,замужем,2.0
54,Носова Л.Г.,15.07.1974,ж,08.08.1997,4300,незамужем,NaN
56,Петухова Т.Н.,06.03.1979,ж,08.10.1998,3500,незамужем,NaN
57,Пименова О.Н.,01.09.1957,ж,11.08.1990,5600,замужем,3.0
58,Позднякова Т.И.,15.07.1974,ж,08.08.1997,4300,разведена,NaN
60,Пономарева Л.А.,04.09.1945,ж,21.03.1986,4000,замужем,3.0
62,Родникова С.В.,01.09.1957,ж,11.08.1990,5600,замужем,1.0
63,Романова А.И.,12.12.1977,ж,08.08.1997,4000,незамужем,1.0
64,Романова З.В.,06.04.1974,ж,23.11.1998,4600,замужем,1.0
71,Смирнова И.В.,02.01.1948,ж,23.11.1985,5600,замужем,2.0
72,Соколова А.В.,02.01.1948,ж,23.11.1985,5600,разведена,2.0
73,Степина Т.И.,16.12.1976,ж,05.09.1997,3700,замужем,1.0
77,Туровская Н.С.,08.05.1979,ж,05.09.1997,5600,незамужем,NaN
78,Тяпкина Л.А.,06.06.1952,ж,08.10.1980,4000,замужем,NaN
79,Укладчикова Н.И.,16.12.1976,ж,05.09.1997,3700,незамужем,NaN
81,Ушакова И.И.,06.05.1979,ж,05.09.1997,5600,незамужем,NaN
84,Федорова З.А.,02.04.1952,ж,23.09.1992,4600,замужем,NaN
85,Федюшкина М.А.,02.04.1950,ж,25.07.1994,4600,замужем,1.0
87,Филатова О.В.,21.01.1942,ж,01.11.1980,4600,замужем,NaN
88,Харькова Л.В.,23.08.1980,ж,05.09.1997,4500,незамужем,NaN
89,Хромова Л.В.,21.01.1937,ж,01.11.1980,4600,замужем,NaN
90,Хромова Л.В.,07.08.1938,ж,12.06.1985,3000,замужем,1.0
91,Червякова Н.С.,06.06.1946,ж,08.10.1980,4000,замужем,NaN
93,Чигрина А.Е.,29.07.1939,ж,09.12.1985,4500,замужем,1.0
94,Чиркина А.М.,07.08.1938,ж,12.06.1985,3000,замужем,1.0
95,Шафеева Н.К.,29.07.1939,ж,09.12.1985,4500,замужем,1.0
98,Якимова Н.М.,16.05.1973,ж,07.09.1999,3000,замужем,2.0
99,Яфарова Т.Н.,04.09.1945,ж,21.03.1986,4000,замужем,2.0

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
0,Алистратов А.А.,27.10.1975,м,08.09.1997,4000,женат,1.0
1,Анохин Н.И.,11.12.1948,м,23.05.1986,5000,разведен,1.0
6,Ахундов О.Т.,01.05.1967,м,23.05.1986,4400,холост,NaN
8,Белорусец И.А.,04.11.1960,м,09.03.1989,4000,холост,NaN
10,Булгаков Ю.В.,01.05.1957,м,09.06.1985,3000,женат,1.0
13,Варлаков В.Н.,23.10.1966,м,12.09.1995,5000,холост,NaN
18,Гостев И.И.,22.11.1969,м,13.09.1996,6000,женат,2.0
20,Гринченко М.В.,08.12.1954,м,06.09.1985,4300,женат,1.0
25,Ежиков А.В.,14.02.1963,м,01.11.1990,6000,женат,4.0
27,Зайцев Б.П.,20.08.1959,м,05.10.1995,5000,женат,1.0
31,Кирюхин В.Н.,20.08.1954,м,09.12.1985,4900,женат,2.0
34,Колесников И.С.,25.03.1964,м,05.03.1985,6000,холост,NaN
41,Леонтьев В.К.,06.01.1979,м,11.08.1990,2700,холост,NaN
42,Локшин Я.С.,17.01.1961,м,06.09.1985,5000,женат,1.0
43,Львов Г.Н.,13.07.1947,м,09.12.1990,3000,женат,3.0
44,Малахов Г.И.,08.12.1954,м,06.09.1985,4300,женат,1.0
45,Марченко А.Н.,03.10.1936,м,04.08.1980,7000,женат,NaN
46,Медведев Б.М.,24.04.1960,м,04.05.1994,5600,женат,3.0
47,Мельников А.С.,11.07.1961,м,21.03.1986,5400,разведен,1.0
48,Минаев Ю.В.,08.08.1956,м,09.12.1987,3000,холост,NaN
51,Муленков Е.И.,09.11.1969,м,20.12.1992,4300,холост,1.0
55,Овчинников А.М.,09.11.1969,м,20.12.1992,4300,женат,1.0
59,Полибин А.А.,05.05.1967,м,04.05.1984,4400,женат,NaN
61,Реутенко Р.В.,06.11.1978,м,20.12.1992,4700,холост,NaN
65,Рыбальский Г.Л.,12.10.1958,м,23.05.1995,5600,женат,2.0
66,Рыжов А.В.,12.10.1958,м,23.05.1995,5600,женат,2.0
67,Сарайкин В.Ф.,05.06.1965,м,12.06.1985,4900,женат,1.0
68,Сафронов В.В.,06.04.1979,м,08.10.1998,2400,холост,NaN
69,Семенов М.П.,09.01.1970,м,11.08.1990,4700,женат,NaN
70,Скворцов С.М.,06.04.1979,м,08.10.1998,3800,холост,NaN
74,Страшнов Г.Г.,06.02.1954,м,23.05.1995,4500,женат,1.0
75,Сулдин В.Г.,11.03.1979,м,08.10.1998,3500,холост,NaN
76,Сыроватский И.В.,25.04.1977,м,23.11.1998,4400,женат,1.0
80,Устинов А.А.,31.03.1934,м,09.06.1985,4700,разведен,NaN
82,Ушкаров Н.А.,13.11.1979,м,23.11.2001,4000,холост,NaN
83,Федоров Д.М.,31.03.1932,м,09.06.1975,7700,женат,2.0
86,Фетисов А.Н.,11.12.1948,м,23.05.1986,4000,женат,1.0
92,Чернов Е.В.,15.05.1972,м,06.09.2001,5500,женат,1.0
96,Шиманюк Н.И.,06.11.1979,м,23.11.1998,4000,холост,NaN
97,Элиава Т.М.,19.05.1981,м,10.09.1997,3700,холост,NaN

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей,Возраст
2,Антонова И.П.,04.12.1951,ж,09.05.1988,4300,замужем,1.0,70.0
3,Артемова Г.А.,06.08.1979,ж,05.09.1997,4500,незамужем,NaN,42.0
4,Афоничева Л.К.,09.01.1952,ж,05.10.1985,4900,замужем,1.0,69.0
5,Афоничева Л.В.,08.06.1978,ж,22.09.1998,3000,замужем,NaN,43.0
7,Бегунова С.А.,20.05.1973,ж,11.09.1997,4400,замужем,1.0,48.0
9,Бизюкова Г.П.,01.05.1957,ж,09.06.1985,4000,замужем,1.0,64.0
11,Быкова И.А.,12.01.1958,ж,25.07.1994,5600,замужем,2.0,63.0
12,Вантеева Л.В.,12.01.1958,ж,25.07.1994,4500,замужем,2.0,63.0
14,Васильева Е.Г.,09.01.1952,ж,05.10.1985,4900,замужем,1.0,69.0
15,Вуколова О.В.,14.02.1963,ж,01.11.1990,3500,замужем,2.0,58.0
16,Гаранина Г.П.,05.06.1965,ж,12.06.1985,3500,замужем,1.0,56.0
17,Гордеева Н.А.,16.11.1953,ж,05.03.1985,4100,замужем,NaN,68.0
19,Грачева О.Е.,13.05.1967,ж,14.09.2000,4500,замужем,NaN,54.0
21,Гусева И.А.,06.06.1956,ж,09.12.1987,4900,разведена,1.0,65.0
22,Дзебоева Н.А.,20.08.1954,ж,09.12.1985,4600,замужем,2.0,67.0
23,Дмитриева З.Е.,22.09.1980,ж,09.05.1998,4700,незамужем,NaN,41.0
24,Дробикова С.А.,11.07.1961,ж,21.03.1986,5600,замужем,1.0,60.0
26,Ермолаева Е.И.,01.05.1967,ж,23.05.1986,4300,незамужем,NaN,54.0
28,Зайцева Т.Н.,22.09.1980,ж,09.05.1998,3800,незамужем,NaN,41.0
29,Захарова В.В.,24.06.1964,ж,15.09.1995,4300,замужем,2.0,57.0
30,Истратова Е.Н.,25.03.1964,ж,05.03.1985,3000,замужем,2.0,57.0
32,Ковалева М.Г.,20.08.1959,ж,05.10.1995,4500,замужем,1.0,62.0
33,Колганова В.В.,07.08.1951,ж,04.08.1980,4450,замужем,1.0,70.0
35,Конюхова Л.Н.,17.01.1951,ж,06.09.1985,3000,разведена,1.0,70.0
36,Корчагина О.С.,05.05.1967,ж,04.05.1984,4400,замужем,1.0,54.0
37,Курдина С.Х.,16.11.1953,ж,05.03.1985,4100,замужем,NaN,68.0
38,Лазькова Л.В.,06.11.1978,ж,20.12.1992,4700,незамужем,NaN,43.0
39,Ларшина Н.П.,06.12.1978,ж,08.08.1997,4000,незамужем,1.0,43.0
40,Леонова Е.И.,13.07.1947,ж,09.12.1990,3000,замужем,3.0,74.0
49,Михайлова Т.В.,06.02.1954,ж,23.05.1995,3000,замужем,3.0,67.0
50,Моисеева В.Б.,07.08.1962,ж,04.09.1980,4450,замужем,2.0,59.0
52,Муравьева В.С.,03.10.1955,ж,04.08.1980,3000,незамужем,NaN,66.0
53,Нарольская Т.С.,14.05.1962,ж,04.05.1994,4000,замужем,2.0,59.0
54,Носова Л.Г.,15.07.1974,ж,08.08.1997,4300,незамужем,NaN,47.0
56,Петухова Т.Н.,06.03.1979,ж,08.10.1998,3500,незамужем,NaN,42.0
57,Пименова О.Н.,01.09.1957,ж,11.08.1990,5600,замужем,3.0,64.0
58,Позднякова Т.И.,15.07.1974,ж,08.08.1997,4300,разведена,NaN,47.0
60,Пономарева Л.А.,04.09.1945,ж,21.03.1986,4000,замужем,3.0,76.0
62,Родникова С.В.,01.09.1957,ж,11.08.1990,5600,замужем,1.0,64.0
63,Романова А.И.,12.12.1977,ж,08.08.1997,4000,незамужем,1.0,44.0
64,Романова З.В.,06.04.1974,ж,23.11.1998,4600,замужем,1.0,47.0
71,Смирнова И.В.,02.01.1948,ж,23.11.1985,5600,замужем,2.0,73.0
72,Соколова А.В.,02.01.1948,ж,23.11.1985,5600,разведена,2.0,73.0
73,Степина Т.И.,16.12.1976,ж,05.09.1997,3700,замужем,1.0,45.0
77,Туровская Н.С.,08.05.1979,ж,05.09.1997,5600,незамужем,NaN,42.0
78,Тяпкина Л.А.,06.06.1952,ж,08.10.1980,4000,замужем,NaN,69.0
79,Укладчикова Н.И.,16.12.1976,ж,05.09.1997,3700,незамужем,NaN,45.0
81,Ушакова И.И.,06.05.1979,ж,05.09.1997,5600,незамужем,NaN,42.0
84,Федорова З.А.,02.04.1952,ж,23.09.1992,4600,замужем,NaN,69.0
85,Федюшкина М.А.,02.04.1950,ж,25.07.1994,4600,замужем,1.0,71.0
87,Филатова О.В.,21.01.1942,ж,01.11.1980,4600,замужем,NaN,79.0
88,Харькова Л.В.,23.08.1980,ж,05.09.1997,4500,незамужем,NaN,41.0
89,Хромова Л.В.,21.01.1937,ж,01.11.1980,4600,замужем,NaN,84.0
90,Хромова Л.В.,07.08.1938,ж,12.06.1985,3000,замужем,1.0,83.0
91,Червякова Н.С.,06.06.1946,ж,08.10.1980,4000,замужем,NaN,75.0
93,Чигрина А.Е.,29.07.1939,ж,09.12.1985,4500,замужем,1.0,82.0
94,Чиркина А.М.,07.08.1938,ж,12.06.1985,3000,замужем,1.0,83.0
95,Шафеева Н.К.,29.07.1939,ж,09.12.1985,4500,замужем,1.0,82.0
98,Якимова Н.М.,16.05.1973,ж,07.09.1999,3000,замужем,2.0,48.0
99,Яфарова Т.Н.,04.09.1945,ж,21.03.1986,4000,замужем,2.0,76.0

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей,Стаж
0,Алистратов А.А.,27.10.1975,м,08.09.1997,4000,женат,1.0,46.0
1,Анохин Н.И.,11.12.1948,м,23.05.1986,5000,разведен,1.0,73.0
6,Ахундов О.Т.,01.05.1967,м,23.05.1986,4400,холост,NaN,54.0
8,Белорусец И.А.,04.11.1960,м,09.03.1989,4000,холост,NaN,61.0
10,Булгаков Ю.В.,01.05.1957,м,09.06.1985,3000,женат,1.0,64.0
13,Варлаков В.Н.,23.10.1966,м,12.09.1995,5000,холост,NaN,55.0
18,Гостев И.И.,22.11.1969,м,13.09.1996,6000,женат,2.0,52.0
20,Гринченко М.В.,08.12.1954,м,06.09.1985,4300,женат,1.0,67.0
25,Ежиков А.В.,14.02.1963,м,01.11.1990,6000,женат,4.0,58.0
27,Зайцев Б.П.,20.08.1959,м,05.10.1995,5000,женат,1.0,62.0
31,Кирюхин В.Н.,20.08.1954,м,09.12.1985,4900,женат,2.0,67.0
34,Колесников И.С.,25.03.1964,м,05.03.1985,6000,холост,NaN,57.0
41,Леонтьев В.К.,06.01.1979,м,11.08.1990,2700,холост,NaN,42.0
42,Локшин Я.С.,17.01.1961,м,06.09.1985,5000,женат,1.0,60.0
43,Львов Г.Н.,13.07.1947,м,09.12.1990,3000,женат,3.0,74.0
44,Малахов Г.И.,08.12.1954,м,06.09.1985,4300,женат,1.0,67.0
45,Марченко А.Н.,03.10.1936,м,04.08.1980,7000,женат,NaN,85.0
46,Медведев Б.М.,24.04.1960,м,04.05.1994,5600,женат,3.0,61.0
47,Мельников А.С.,11.07.1961,м,21.03.1986,5400,разведен,1.0,60.0
48,Минаев Ю.В.,08.08.1956,м,09.12.1987,3000,холост,NaN,65.0
51,Муленков Е.И.,09.11.1969,м,20.12.1992,4300,холост,1.0,52.0
55,Овчинников А.М.,09.11.1969,м,20.12.1992,4300,женат,1.0,52.0
59,Полибин А.А.,05.05.1967,м,04.05.1984,4400,женат,NaN,54.0
61,Реутенко Р.В.,06.11.1978,м,20.12.1992,4700,холост,NaN,43.0
65,Рыбальский Г.Л.,12.10.1958,м,23.05.1995,5600,женат,2.0,63.0
66,Рыжов А.В.,12.10.1958,м,23.05.1995,5600,женат,2.0,63.0
67,Сарайкин В.Ф.,05.06.1965,м,12.06.1985,4900,женат,1.0,56.0
68,Сафронов В.В.,06.04.1979,м,08.10.1998,2400,холост,NaN,42.0
69,Семенов М.П.,09.01.1970,м,11.08.1990,4700,женат,NaN,51.0
70,Скворцов С.М.,06.04.1979,м,08.10.1998,3800,холост,NaN,42.0
74,Страшнов Г.Г.,06.02.1954,м,23.05.1995,4500,женат,1.0,67.0
75,Сулдин В.Г.,11.03.1979,м,08.10.1998,3500,холост,NaN,42.0
76,Сыроватский И.В.,25.04.1977,м,23.11.1998,4400,женат,1.0,44.0
80,Устинов А.А.,31.03.1934,м,09.06.1985,4700,разведен,NaN,87.0
82,Ушкаров Н.А.,13.11.1979,м,23.11.2001,4000,холост,NaN,42.0
83,Федоров Д.М.,31.03.1932,м,09.06.1975,7700,женат,2.0,89.0
86,Фетисов А.Н.,11.12.1948,м,23.05.1986,4000,женат,1.0,73.0
92,Чернов Е.В.,15.05.1972,м,06.09.2001,5500,женат,1.0,49.0
96,Шиманюк Н.И.,06.11.1979,м,23.11.1998,4000,холост,NaN,42.0
97,Элиава Т.М.,19.05.1981,м,10.09.1997,3700,холост,NaN,40.0

In [17]:
#Отобрать только сотрудников, имеющих детей и оклад, меньше среднего оклада сотрудников.
temp = data.Оклад.mean()
print(temp)
display(data[(data['Оклад'] < temp) & (data['Кол-во детей'] > 0)])

4404.0

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
0,Алистратов А.А.,27.10.1975,м,08.09.1997,4000,женат,1.0
2,Антонова И.П.,04.12.1951,ж,09.05.1988,4300,замужем,1.0
7,Бегунова С.А.,20.05.1973,ж,11.09.1997,4400,замужем,1.0
9,Бизюкова Г.П.,01.05.1957,ж,09.06.1985,4000,замужем,1.0
10,Булгаков Ю.В.,01.05.1957,м,09.06.1985,3000,женат,1.0
15,Вуколова О.В.,14.02.1963,ж,01.11.1990,3500,замужем,2.0
16,Гаранина Г.П.,05.06.1965,ж,12.06.1985,3500,замужем,1.0
20,Гринченко М.В.,08.12.1954,м,06.09.1985,4300,женат,1.0
29,Захарова В.В.,24.06.1964,ж,15.09.1995,4300,замужем,2.0
30,Истратова Е.Н.,25.03.1964,ж,05.03.1985,3000,замужем,2.0
35,Конюхова Л.Н.,17.01.1951,ж,06.09.1985,3000,разведена,1.0
36,Корчагина О.С.,05.05.1967,ж,04.05.1984,4400,замужем,1.0
39,Ларшина Н.П.,06.12.1978,ж,08.08.1997,4000,незамужем,1.0
40,Леонова Е.И.,13.07.1947,ж,09.12.1990,3000,замужем,3.0
43,Львов Г.Н.,13.07.1947,м,09.12.1990,3000,женат,3.0
44,Малахов Г.И.,08.12.1954,м,06.09.1985,4300,женат,1.0
49,Михайлова Т.В.,06.02.1954,ж,23.05.1995,3000,замужем,3.0
51,Муленков Е.И.,09.11.1969,м,20.12.1992,4300,холост,1.0
53,Нарольская Т.С.,14.05.1962,ж,04.05.1994,4000,замужем,2.0
55,Овчинников А.М.,09.11.1969,м,20.12.1992,4300,женат,1.0
60,Пономарева Л.А.,04.09.1945,ж,21.03.1986,4000,замужем,3.0
63,Романова А.И.,12.12.1977,ж,08.08.1997,4000,незамужем,1.0
73,Степина Т.И.,16.12.1976,ж,05.09.1997,3700,замужем,1.0
76,Сыроватский И.В.,25.04.1977,м,23.11.1998,4400,женат,1.0
86,Фетисов А.Н.,11.12.1948,м,23.05.1986,4000,женат,1.0
90,Хромова Л.В.,07.08.1938,ж,12.06.1985,3000,замужем,1.0
94,Чиркина А.М.,07.08.1938,ж,12.06.1985,3000,замужем,1.0
98,Якимова Н.М.,16.05.1973,ж,07.09.1999,3000,замужем,2.0
99,Яфарова Т.Н.,04.09.1945,ж,21.03.1986,4000,замужем,2.0

In [19]:
#Выяснить, есть ли в списке юбиляры (кому в текущем году исполнилось количество лет, оканчивающееся на нуль или пять),
#получить этот список в виде DataFrame.
def function1(argument):
    temp = list()
    for i in argument:
        temp.append(int(i[6:10]))
    return pd.Series(temp)

display(data[(2021 - function1(data['Дата рождения'])) % 5 == 0])

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
2,Антонова И.П.,04.12.1951,ж,09.05.1988,4300,замужем,1.0
13,Варлаков В.Н.,23.10.1966,м,12.09.1995,5000,холост,NaN
21,Гусева И.А.,06.06.1956,ж,09.12.1987,4900,разведена,1.0
24,Дробикова С.А.,11.07.1961,ж,21.03.1986,5600,замужем,1.0
33,Колганова В.В.,07.08.1951,ж,04.08.1980,4450,замужем,1.0
35,Конюхова Л.Н.,17.01.1951,ж,06.09.1985,3000,разведена,1.0
42,Локшин Я.С.,17.01.1961,м,06.09.1985,5000,женат,1.0
45,Марченко А.Н.,03.10.1936,м,04.08.1980,7000,женат,NaN
47,Мельников А.С.,11.07.1961,м,21.03.1986,5400,разведен,1.0
48,Минаев Ю.В.,08.08.1956,м,09.12.1987,3000,холост,NaN
73,Степина Т.И.,16.12.1976,ж,05.09.1997,3700,замужем,1.0
79,Укладчикова Н.И.,16.12.1976,ж,05.09.1997,3700,незамужем,NaN
91,Червякова Н.С.,06.06.1946,ж,08.10.1980,4000,замужем,NaN
97,Элиава Т.М.,19.05.1981,м,10.09.1997,3700,холост,NaN

In [20]:
#Получить DataFrame, в котором рассчитывается количество сотрудников по категориям:
#женат, замужем, холост, незамужем, разведен, разведена. Полученный DataFrame сохранить на github
#в формате csv с указанием ссылки.
new_df = pd.DataFrame(columns = ['Женат','Замужем','Холост','Незамужем','Разведен','Разведена'])
new_df.loc[0, 'Женат'] = data[data['Семейное положение'] == 'женат']['Семейное положение'].count()
new_df.loc[0, 'Замужем'] = data[data['Семейное положение'] == 'замужем']['Семейное положение'].count()
new_df.loc[0, 'Холост'] = data[data['Семейное положение'] == 'холост']['Семейное положение'].count()
new_df.loc[0, 'Незамужем'] = data[data['Семейное положение'] == 'незамужем']['Семейное положение'].count()
new_df.loc[0, 'Разведен'] = data[data['Семейное положение'] == 'разведен']['Семейное положение'].count()
new_df.loc[0, 'Разведена'] = data[data['Семейное положение'] == 'разведена']['Семейное положение'].count()
display(new_df)

  Женат Замужем Холост Незамужем Разведен Разведена
0    23      42     14        14        3         4

In [21]:
new_df.to_csv('Test1_Dunaykin.csv')